import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';
import { processAudioTrack } from '@/lib/audio/processor';
import { transcribeAudioWithTimestamps } from '@/lib/transcription';
import { saveRecording, getAudioAssets } from '@/lib/db';
import { FilterPresetType, VinylStyleType, Recording } from '@/types';

// Enforce Node.js runtime for FFmpeg execution
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

function generateSlug(length: number = 8): string {
  const chars = 'abcdefghjkmnpqrstuvwxyz23456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

export async function POST(req: NextRequest) {
  const sessionId = uuidv4();
  const tmpDir = path.join(process.cwd(), 'tmp');
  if (!fs.existsSync(tmpDir)) {
    fs.mkdirSync(tmpDir, { recursive: true });
  }

  const publicRecordsDir = path.join(process.cwd(), 'public', 'records');
  if (!fs.existsSync(publicRecordsDir)) {
    fs.mkdirSync(publicRecordsDir, { recursive: true });
  }

  const voiceFilePath = path.join(tmpDir, `voice_${sessionId}.webm`);
  const outputFilePath = path.join(tmpDir, `output_${sessionId}.mp3`);
  const finalPublicMp3 = path.join(publicRecordsDir, `record_${sessionId}.mp3`);

  const tempFilesToPurge: string[] = [voiceFilePath, outputFilePath];

  try {
    const formData = await req.formData();
    const audioFile = formData.get('audio') as File | null;

    if (!audioFile) {
      return NextResponse.json(
        { error: 'No audio recording file provided in payload.' },
        { status: 400 }
      );
    }

    const title = (formData.get('title') as string) || 'Untitled Memory';
    const recipientName = (formData.get('recipientName') as string) || '';
    const senderName = (formData.get('senderName') as string) || '';
    const filterPreset = ((formData.get('filterPreset') as string) || 'gramophone') as FilterPresetType;
    const crackleIntensity = parseFloat((formData.get('crackleIntensity') as string) || '0.15');
    const bgMusicId = (formData.get('bgMusicId') as string) || null;
    const vinylStyle = ((formData.get('vinylStyle') as string) || 'classic_red') as VinylStyleType;

    // 1. Write incoming audio blob to local process.cwd()/tmp/voice_[uuid].webm
    const arrayBuffer = await audioFile.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    await fs.promises.writeFile(voiceFilePath, buffer);

    // Resolve background music & crackle file paths
    let bgMusicFilePath: string | null = null;
    let crackleFilePath: string | null = path.join(process.cwd(), 'public', 'audio', 'crackle-vintage.mp3');

    if (bgMusicId && bgMusicId !== 'none') {
      const allAssets = await getAudioAssets();
      const asset = allAssets.find((a) => a.id === bgMusicId || a.file_url.includes(bgMusicId));
      if (asset) {
        if (asset.file_url.startsWith('/')) {
          bgMusicFilePath = path.join(process.cwd(), 'public', asset.file_url);
        } else {
          bgMusicFilePath = asset.file_url;
        }
      }
    }

    // 2. Synthesize audio via fluent-ffmpeg complex filter chain
    console.log(`[AudioEngine] Synthesizing audio session: ${sessionId} (filter: ${filterPreset})`);
    const { durationSeconds } = await processAudioTrack({
      voiceFilePath,
      outputFilePath,
      filterPreset,
      crackleIntensity,
      bgMusicFilePath,
      crackleFilePath,
    });

    // 3. Move/copy output to public storage
    if (fs.existsSync(outputFilePath)) {
      await fs.promises.copyFile(outputFilePath, finalPublicMp3);
    } else {
      throw new Error('Processed output file was not generated by FFmpeg.');
    }

    const processedAudioUrl = `/records/record_${sessionId}.mp3`;
    const rawVoiceUrl = processedAudioUrl;

    // 4. Send raw voice buffer to OpenAI Whisper API (or smart word alignment fallback)
    console.log(`[AudioEngine] Generating AI word-by-word transcription...`);
    const transcriptJson = await transcribeAudioWithTimestamps(
      voiceFilePath,
      durationSeconds,
      title
    );

    // 5. Generate unique 8-character slug and persist to DB
    const slug = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 20)}-${generateSlug(6)}`;

    const newRecording: Recording = {
      id: sessionId,
      slug,
      user_id: null,
      title,
      recipient_name: recipientName,
      sender_name: senderName,
      processed_audio_url: processedAudioUrl,
      raw_voice_url: rawVoiceUrl,
      transcript_json: transcriptJson,
      vinyl_style: vinylStyle,
      filter_preset: filterPreset,
      crackle_intensity: crackleIntensity,
      bg_music_id: bgMusicId,
      views: 0,
      created_at: new Date().toISOString(),
      duration_seconds: durationSeconds,
    };

    await saveRecording(newRecording);
    console.log(`[AudioEngine] Successfully pressed vinyl record: /play/${slug}`);

    return NextResponse.json({
      success: true,
      recording: newRecording,
      slug: newRecording.slug,
      playUrl: `/play/${newRecording.slug}`,
    });
  } catch (error: any) {
    console.error('[AudioEngine] Fatal processing error:', error);
    return NextResponse.json(
      {
        error: error.message || 'Server failed to synthesize vinyl audio recording.',
      },
      { status: 500 }
    );
  } finally {
    // 7. ALWAYS purge temporary files in process.cwd()/tmp/ using fs.promises.unlink
    for (const file of tempFilesToPurge) {
      try {
        if (fs.existsSync(file)) {
          await fs.promises.unlink(file);
        }
      } catch (cleanupErr) {
        console.warn(`[AudioEngine] Cleanup warning for ${file}:`, cleanupErr);
      }
    }
  }
}
