package com.vynylrecord.app.core.storage

import android.content.Context
import java.io.File

/**
 * Where everything lives.
 *
 * Every path in the app comes from here, which is what makes "where did my record go" answerable: the
 * layout is small enough to hold in your head, and the Settings screen's storage panel is computed by
 * walking these three roots and nothing else.
 *
 * ```
 * files/
 *   records/{recordId}/source.wav      the capture or the imported file, kept as PCM
 *                      master.wav      the pressed record
 *                      cover.png       the sleeve artwork
 *                      waveform.json   peaks for the library card
 *   assets/{assetId}.wav               imported background music, sound effects, textures
 *   exports/                           finished files the share sheet hands out
 * cache/
 *   render/{jobId}/                    a render in progress; deleted the moment it is done
 *   asset-staging/                     bundled assets copied out of the APK so a decoder can read them
 *   decoded/                           decoded background beds, cached so a re-render is fast
 *   shared/                            files on their way to another app through FileProvider
 * ```
 *
 * Nothing is stored outside the app's own directory except an export the user explicitly saved through
 * the system file picker, and no storage permission is needed for any of it: `filesDir` and `cacheDir`
 * are the app's by right.
 */
object StorageLayout {

    const val RECORDS = "records"
    const val ASSETS = "assets"
    const val EXPORTS = "exports"
    const val RENDER = "render"
    const val ASSET_STAGING = "asset-staging"
    const val DECODED = "decoded"
    const val SHARED = "shared"

    const val SOURCE_NAME = "source.wav"
    const val MASTER_NAME = "master.wav"
    const val ARTWORK_NAME = "cover.png"
    const val WAVEFORM_NAME = "waveform.json"

    fun filesRoot(context: Context): File = context.filesDir
    fun cacheRoot(context: Context): File = context.cacheDir

    fun recordsRoot(root: File): File = File(root, RECORDS)
    fun assetsRoot(root: File): File = File(root, ASSETS)
    fun exportsRoot(root: File): File = File(root, EXPORTS)

    fun recordDirectory(root: File, recordId: String): File = File(recordsRoot(root), safeId(recordId))

    fun sourceFile(root: File, recordId: String): File = File(recordDirectory(root, recordId), SOURCE_NAME)
    fun masterFile(root: File, recordId: String): File = File(recordDirectory(root, recordId), MASTER_NAME)
    fun artworkFile(root: File, recordId: String): File = File(recordDirectory(root, recordId), ARTWORK_NAME)
    fun waveformFile(root: File, recordId: String): File = File(recordDirectory(root, recordId), WAVEFORM_NAME)

    /** Assets keep their own extension so a file manager dump of the directory stays readable. */
    fun assetFile(root: File, assetId: String, extension: String = "wav"): File =
        File(assetsRoot(root), "${safeId(assetId)}.$extension")

    fun renderDirectory(cache: File, jobId: String): File = File(File(cache, RENDER), safeId(jobId))
    fun renderMaster(cache: File, jobId: String): File = File(renderDirectory(cache, jobId), MASTER_NAME)
    fun stagingRoot(cache: File): File = File(cache, ASSET_STAGING)
    fun decodedRoot(cache: File): File = File(cache, DECODED)
    fun sharedRoot(cache: File): File = File(cache, SHARED)

    /**
     * Keeps a user-supplied id from walking out of its directory.
     *
     * Ids are UUIDs generated by the app, so this is defence in depth rather than a live risk — but a
     * crafted `.vynyl` bundle can carry an id of its own, and a path with `../` in it must never be
     * joined to the app's own storage.
     */
    fun safeId(id: String): String {
        val cleaned = id.filter { it.isLetterOrDigit() || it == '-' || it == '_' }
        return if (cleaned.isEmpty()) "unnamed" else cleaned.take(64)
    }

    /** Creates the directory a path lives in, and returns the path. */
    fun ensureParent(file: File): File {
        file.parentFile?.mkdirs()
        return file
    }

    /** Total bytes under [root], for the Settings storage panel. */
    fun sizeOf(root: File): Long {
        if (!root.exists()) return 0L
        if (root.isFile) return root.length()
        var total = 0L
        val children = root.listFiles() ?: return 0L
        for (child in children) total += sizeOf(child)
        return total
    }

    /** Deletes a directory tree, bottom-up. Returns how many bytes were freed. */
    fun deleteTree(root: File): Long {
        val freed = sizeOf(root)
        root.deleteRecursively()
        return freed
    }

    /** Everything the cache holds, for the "clear cache" button. */
    fun renderCacheBytes(cache: File): Long = sizeOf(File(cache, RENDER))

    fun assetCacheBytes(cache: File): Long = sizeOf(stagingRoot(cache)) + sizeOf(decodedRoot(cache))

    /**
     * Removes render scratch, staged assets and share copies.
     *
     * Exports are deliberately left alone: the button is labelled "temporary files", and the export
     * directory holds files the user asked for. A copy staged for the share sheet is disposable because
     * the export it came from is still there.
     */
    fun clearCache(cache: File): Long {
        var freed = 0L
        freed += deleteTree(File(cache, RENDER))
        freed += deleteTree(stagingRoot(cache))
        freed += deleteTree(decodedRoot(cache))
        freed += deleteTree(sharedRoot(cache))
        return freed
    }

    /**
     * A record's own directory plus its assets, which is what "how much space is this record using" means.
     */
    fun recordBytes(root: File, recordId: String): Long = sizeOf(recordDirectory(root, recordId))
}
