package com.vynylrecord.app.core.model

import java.util.UUID

/**
 * What a local asset is for.
 *
 * The three categories are the web application's `AudioCategory` values, kept as-is so a bundle's
 * manifest is readable by both. A background track is *music*; a surface texture is a room or a
 * turntable bed; a sound effect is a one-shot like a needle drop.
 */
enum class AssetCategory(val id: String, val label: String, val description: String) {
    BACKGROUND_MUSIC(
        id = "bg_music",
        label = "Background music",
        description = "Mixed under the voice. This is the one that appears in the Studio.",
    ),
    SURFACE_TEXTURE(
        id = "surface_texture",
        label = "Surface texture",
        description = "A room or turntable bed, layered under the vinyl surface.",
    ),
    SOUND_EFFECT(
        id = "sound_effect",
        label = "Sound effect",
        description = "A one-shot, such as a needle drop before the voice.",
    ),
    ;

    companion object {
        fun fromId(id: String?): AssetCategory =
            entries.firstOrNull { it.id == id } ?: BACKGROUND_MUSIC
    }
}

/**
 * A piece of audio the Studio can mix under a voice.
 *
 * Assets come from two places and the difference is preserved rather than flattened: a **bundled** asset
 * ships inside the APK and lives in `assets/`, so it has no file on disk to measure and can be disabled
 * but never deleted; an **imported** asset is a copy of a document the user picked, sitting in
 * app-private storage, and it can be deleted. Both are addressed by [id] from a record, so replacing a
 * file with another of the same id keeps every record that used it working.
 */
data class AudioAsset(
    val id: String = UUID.randomUUID().toString(),
    val title: String = "",
    val category: AssetCategory = AssetCategory.BACKGROUND_MUSIC,
    /**
     * Path relative to `files/assets/{id}/`, or null for a bundled asset.
     *
     * A bundled asset is read from the APK through `AssetManager`, which is why it has no path: it can
     * never be missing, and it costs no storage beyond the APK the user already installed.
     */
    val sourcePath: String? = null,
    /** The `assets/` entry, e.g. `audio/bg-guitar.mp3`. Null for imported assets. */
    val bundledResourceName: String? = null,
    val isBundled: Boolean = false,
    val enabled: Boolean = true,
    val defaultVolume: Float = 0.18f,
    val trimStartMilliseconds: Long = 0L,
    val trimEndMilliseconds: Long = 0L,
    val durationMilliseconds: Long = 0L,
    val sizeBytes: Long = 0L,
    val createdAt: Long = System.currentTimeMillis(),
) {
    val displayTitle: String get() = title.ifBlank { bundledResourceName ?: "Untitled asset" }

    val isMusic: Boolean get() = category == AssetCategory.BACKGROUND_MUSIC

    /** How long the user's chosen cut runs, or the whole file when they have not trimmed it. */
    val effectiveDurationMs: Long
        get() {
            if (durationMilliseconds <= 0L) return 0L
            val start = trimStartMilliseconds.coerceIn(0L, durationMilliseconds)
            val end = if (trimEndMilliseconds <= start) durationMilliseconds else trimEndMilliseconds
            return (end.coerceIn(start, durationMilliseconds) - start)
        }

    val durationLabel: String
        get() {
            val total = effectiveDurationMs / 1000L
            return "%d:%02d".format(total / 60L, total % 60L)
        }

    val sizeLabel: String get() = Record.formatBytes(sizeBytes)

    companion object {
        /**
         * The bundled library.
         *
         * Every entry is generated by `tools/generate_bundled_assets.py` in this repository — original
         * synthesis, no third-party masters, no sample libraries, no downloads. They are named the same
         * as the web application's `public/audio/` files so a reader can match them up one for one.
         */
        val BUNDLED: List<AudioAsset> = listOf(
            AudioAsset(
                id = "bundled-bg-guitar",
                title = "Nylon Guitar",
                category = AssetCategory.BACKGROUND_MUSIC,
                bundledResourceName = "audio/bg-guitar.mp3",
                isBundled = true,
                defaultVolume = 0.18f,
                durationMilliseconds = 32_000L,
            ),
            AudioAsset(
                id = "bundled-bg-cello",
                title = "Slow Cello",
                category = AssetCategory.BACKGROUND_MUSIC,
                bundledResourceName = "audio/bg-cello.mp3",
                isBundled = true,
                defaultVolume = 0.16f,
                durationMilliseconds = 32_000L,
            ),
            AudioAsset(
                id = "bundled-bg-accordion",
                title = "Old Accordion",
                category = AssetCategory.BACKGROUND_MUSIC,
                bundledResourceName = "audio/bg-accordion.mp3",
                isBundled = true,
                defaultVolume = 0.15f,
                durationMilliseconds = 32_000L,
            ),
            AudioAsset(
                id = "bundled-bg-rain",
                title = "Rain on Glass",
                category = AssetCategory.BACKGROUND_MUSIC,
                bundledResourceName = "audio/bg-rain.mp3",
                isBundled = true,
                defaultVolume = 0.22f,
                durationMilliseconds = 32_000L,
            ),
            AudioAsset(
                id = "bundled-bg-tape-room",
                title = "Tape Room",
                category = AssetCategory.SURFACE_TEXTURE,
                bundledResourceName = "audio/bg-tape-room.mp3",
                isBundled = true,
                defaultVolume = 0.20f,
                durationMilliseconds = 32_000L,
            ),
            AudioAsset(
                id = "bundled-sfx-needle-drop",
                title = "Needle Drop",
                category = AssetCategory.SOUND_EFFECT,
                bundledResourceName = "audio/needle-drop.mp3",
                isBundled = true,
                defaultVolume = 0.30f,
                durationMilliseconds = 3_000L,
            ),
        )

        /** The bundled tracks that can be mixed under a voice in the Studio. */
        val BUNDLED_MUSIC: List<AudioAsset> = BUNDLED.filter { it.isMusic }
    }
}
