import { FilterPresetConfig, VinylStyleConfig, SiteSettings, PricingPlan, AudioAsset, Recording } from '@/types';

export const VINYL_STYLES: VinylStyleConfig[] = [
  {
    id: 'classic_red',
    name: 'Classic Wax Ruby',
    subtitle: '1920s Velvet Red Core',
    baseColor: '#121212',
    labelColor: '#991b1b',
    grooveColor: '#1e1e1e',
    brassAccent: '#f59e0b',
    isPremium: false,
  },
  {
    id: 'midnight_blue',
    name: 'Midnight Sapphire',
    subtitle: '1940s Blue Note Jazz',
    baseColor: '#0a0e1a',
    labelColor: '#1e3a8a',
    grooveColor: '#172554',
    brassAccent: '#38bdf8',
    isPremium: true,
  },
  {
    id: 'gold_edition',
    name: 'Imperial Gold Master',
    subtitle: 'Presidential Master Edition',
    baseColor: '#1c1917',
    labelColor: '#b45309',
    grooveColor: '#78350f',
    brassAccent: '#fbbf24',
    isPremium: true,
  },
  {
    id: 'vintage_emerald',
    name: 'Vintage Emerald',
    subtitle: 'Art Deco Forest Wax',
    baseColor: '#052e16',
    labelColor: '#166534',
    grooveColor: '#14532d',
    brassAccent: '#4ade80',
    isPremium: true,
  },
  {
    id: 'smoked_obsidian',
    name: 'Smoked Obsidian',
    subtitle: 'Modern Audiophile Carbon',
    baseColor: '#09090b',
    labelColor: '#27272a',
    grooveColor: '#18181b',
    brassAccent: '#e4e4e7',
    isPremium: true,
  },
];

export const FILTER_PRESETS: FilterPresetConfig[] = [
  {
    id: 'clean',
    name: 'Clean Modern',
    year: '2026',
    description: 'High fidelity stereo acoustic clarity with transparent low end.',
    badge: 'Standard',
    isPremium: false,
  },
  {
    id: 'gramophone',
    name: '1920s Gramophone',
    year: '1925',
    description: 'Mid-focused horn resonance, subtle harmonic overdrive, and 78 RPM bandpass.',
    badge: 'Vintage Wax',
    isPremium: false,
  },
  {
    id: 'radio',
    name: '1940s Vintage Radio',
    year: '1942',
    description: 'Vacuum tube saturation with gentle 5Hz amplitude tremolo wave.',
    badge: 'Vacuum Tube',
    isPremium: true,
  },
  {
    id: 'tape',
    name: '1960s Tape Saturation',
    year: '1968',
    description: 'Warm analog magnetic tape compression and rolled-off silky high frequencies.',
    badge: 'Reel-to-Reel',
    isPremium: true,
  },
];

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  hero_copy: {
    headline: 'Preserve Your Voice in Digital Wax',
    subheadline: 'Send a timeless, crackling 3D vinyl message to someone you love. A gift they will listen to forever.',
    cta_text: 'Record Your Memory Now',
  },
  branding_theme: {
    primary_color: '#d97706',
    bg_color: '#0c0a09',
    accent_color: '#78350f',
    font_heading: 'Playfair Display',
    enable_grain_overlay: true,
  },
  faqs: [
    {
      q: 'How does the recipient listen to my vinyl note?',
      a: 'They simply open your custom link on any browser or mobile device. A cinematic 3D turntable appears, gracefully lowers the brass needle onto the rotating vinyl wax, and plays your warm, crackling voice with real-time word-by-word scrolling parchment lyrics.',
    },
    {
      q: 'Can I download the mastered audio file?',
      a: 'Yes! Every pressed record includes a permanent 192kbps MP3 download containing the complete analog master (voice, tube filters, background music, and crackle mixed together).',
    },
    {
      q: 'Do recordings expire?',
      a: 'Never. Digital wax records are permanently stored and preserved. Your loved ones can revisit their anniversary note, grandmother story, or wedding vows decades into the future.',
    },
    {
      q: 'What equipment do I need to record?',
      a: 'Nothing special! Your phone or computer microphone is all you need. Our server-side FFmpeg audio engine applies authentic acoustic gramophone horn filters and tape warmth to make your voice sound like a rare 1920s record.',
    },
  ],
};

export const DEFAULT_PRICING_PLANS: PricingPlan[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    name: 'Vintage Free',
    price_cents: 0,
    stripe_price_id: null,
    max_duration_seconds: 60,
    allowed_filter_presets: ['clean', 'gramophone'],
    allowed_bg_music_ids: ['none', 'rain'],
    allowed_vinyl_styles: ['classic_red'],
    can_adjust_crackle: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    name: 'Gold Master Vinyl',
    price_cents: 900,
    stripe_price_id: 'price_gold_monthly',
    max_duration_seconds: 180,
    allowed_filter_presets: ['clean', 'gramophone', 'radio', 'tape'],
    allowed_bg_music_ids: ['none', 'rain', 'accordion', 'guitar', 'cello'],
    allowed_vinyl_styles: ['classic_red', 'midnight_blue', 'gold_edition', 'vintage_emerald', 'smoked_obsidian'],
    can_adjust_crackle: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    name: 'Heirloom Lifetime',
    price_cents: 2900,
    stripe_price_id: 'price_heirloom_lifetime',
    max_duration_seconds: 600,
    allowed_filter_presets: ['clean', 'gramophone', 'radio', 'tape'],
    allowed_bg_music_ids: ['none', 'rain', 'accordion', 'guitar', 'cello'],
    allowed_vinyl_styles: ['classic_red', 'midnight_blue', 'gold_edition', 'vintage_emerald', 'smoked_obsidian'],
    can_adjust_crackle: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_AUDIO_ASSETS: AudioAsset[] = [
  {
    id: 'a1111111-1111-1111-1111-111111111111',
    title: 'Vintage 1920s Vinyl Crackle Loop',
    category: 'crackle',
    file_url: '/audio/crackle-vintage.mp3',
    is_premium_only: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'a2222222-2222-2222-2222-222222222222',
    title: 'Warm Lo-Fi Rain & Hearth',
    category: 'bg_music',
    file_url: '/audio/bg-rain.mp3',
    is_premium_only: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'a3333333-3333-3333-3333-333333333333',
    title: 'Parisian Cafe Accordion',
    category: 'bg_music',
    file_url: '/audio/bg-accordion.mp3',
    is_premium_only: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'a4444444-4444-4444-4444-444444444444',
    title: 'Acoustic Fireplace Guitar',
    category: 'bg_music',
    file_url: '/audio/bg-guitar.mp3',
    is_premium_only: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'a5555555-5555-5555-5555-555555555555',
    title: 'Cinematic Cello Nocturne',
    category: 'bg_music',
    file_url: '/audio/bg-cello.mp3',
    is_premium_only: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'a6666666-6666-6666-6666-666666666666',
    title: 'Needle Drop on Wax',
    category: 'sound_effect',
    file_url: '/audio/needle-drop.mp3',
    is_premium_only: false,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_RECORDINGS: Recording[] = [
  {
    id: 'rec-0001',
    slug: 'anniversary-eleanor',
    title: 'Our 50th Anniversary Letter',
    recipient_name: 'Eleanor Vance',
    sender_name: 'Arthur Vance',
    processed_audio_url: '/audio/demo-anniversary.mp3',
    raw_voice_url: '/audio/demo-anniversary.mp3',
    transcript_json: [
      { word: 'My', start: 0.0, end: 0.5 },
      { word: 'dearest', start: 0.5, end: 1.1 },
      { word: 'Eleanor,', start: 1.1, end: 1.8 },
      { word: 'every', start: 1.8, end: 2.3 },
      { word: 'single', start: 2.3, end: 2.8 },
      { word: 'day', start: 2.8, end: 3.4 },
      { word: 'with', start: 3.4, end: 3.9 },
      { word: 'you', start: 3.9, end: 4.4 },
      { word: 'feels', start: 4.4, end: 5.0 },
      { word: 'like', start: 5.0, end: 5.5 },
      { word: 'a', start: 5.5, end: 5.9 },
      { word: 'melody', start: 5.9, end: 6.6 },
      { word: 'cut', start: 6.6, end: 7.1 },
      { word: 'into', start: 7.1, end: 7.5 },
      { word: 'gold.', start: 7.5, end: 8.0 },
    ],
    vinyl_style: 'gold_edition',
    filter_preset: 'gramophone',
    crackle_intensity: 0.2,
    bg_music_id: 'a3333333-3333-3333-3333-333333333333',
    views: 1420,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    duration_seconds: 8.0,
  },
  {
    id: 'rec-0002',
    slug: 'grandmas-secret-apple-pie',
    title: "Grandmother's Secret & Love",
    recipient_name: 'Clara & Tommy',
    sender_name: 'Grandma Rose',
    processed_audio_url: '/audio/demo-grandmother.mp3',
    raw_voice_url: '/audio/demo-grandmother.mp3',
    transcript_json: [
      { word: 'Remember', start: 0.0, end: 0.6 },
      { word: 'sweetheart,', start: 0.6, end: 1.3 },
      { word: 'always', start: 1.3, end: 1.9 },
      { word: 'add', start: 1.9, end: 2.5 },
      { word: 'a', start: 2.5, end: 2.9 },
      { word: 'pinch', start: 2.9, end: 3.5 },
      { word: 'of', start: 3.5, end: 3.9 },
      { word: 'cinnamon', start: 3.9, end: 4.7 },
      { word: 'and', start: 4.7, end: 5.2 },
      { word: 'whisk', start: 5.2, end: 5.8 },
      { word: 'with', start: 5.8, end: 6.3 },
      { word: 'love.', start: 6.3, end: 7.0 },
      { word: 'Grandma', start: 7.0, end: 7.7 },
      { word: 'is', start: 7.7, end: 8.1 },
      { word: 'always', start: 8.1, end: 8.7 },
      { word: 'with', start: 8.7, end: 9.1 },
      { word: 'you.', start: 9.1, end: 9.5 },
    ],
    vinyl_style: 'classic_red',
    filter_preset: 'tape',
    crackle_intensity: 0.15,
    bg_music_id: 'a4444444-4444-4444-4444-444444444444',
    views: 890,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    duration_seconds: 9.5,
  },
  {
    id: 'rec-0003',
    slug: 'distance-across-the-sea',
    title: 'Voice Across the Ocean',
    recipient_name: 'Julian',
    sender_name: 'Maya',
    processed_audio_url: '/audio/demo-voice-ocean.mp3',
    raw_voice_url: '/audio/demo-voice-ocean.mp3',
    transcript_json: [
      { word: 'Though', start: 0.0, end: 0.5 },
      { word: 'the', start: 0.5, end: 0.9 },
      { word: 'Pacific', start: 0.9, end: 1.6 },
      { word: 'lies', start: 1.6, end: 2.1 },
      { word: 'between', start: 2.1, end: 2.7 },
      { word: 'us', start: 2.7, end: 3.2 },
      { word: 'tonight,', start: 3.2, end: 3.9 },
      { word: 'listen', start: 3.9, end: 4.5 },
      { word: 'to', start: 4.5, end: 4.9 },
      { word: 'the', start: 4.9, end: 5.3 },
      { word: 'crackle', start: 5.3, end: 6.0 },
      { word: 'of', start: 6.0, end: 6.4 },
      { word: 'this', start: 6.4, end: 6.9 },
      { word: 'record', start: 6.9, end: 7.5 },
      { word: 'and', start: 7.5, end: 7.9 },
      { word: 'know', start: 7.9, end: 8.3 },
      { word: 'I', start: 8.3, end: 8.6 },
      { word: 'am', start: 8.6, end: 8.8 },
      { word: 'home.', start: 8.8, end: 9.0 },
    ],
    vinyl_style: 'midnight_blue',
    filter_preset: 'radio',
    crackle_intensity: 0.25,
    bg_music_id: 'a2222222-2222-2222-2222-222222222222',
    views: 2310,
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    duration_seconds: 9.0,
  },
];
