package com.vynylrecord.app.core.data.repository

import android.content.Context
import android.net.Uri
import android.util.Log
import com.vynylrecord.app.core.audio.AudioDecoder
import com.vynylrecord.app.core.audio.MusicBank
import com.vynylrecord.app.core.audio.StudioFormat
import com.vynylrecord.app.core.data.db.AudioAssetDao
import com.vynylrecord.app.core.data.db.AudioAssetEntity
import com.vynylrecord.app.core.model.AssetCategory
import com.vynylrecord.app.core.model.AudioAsset
import com.vynylrecord.app.core.storage.FileStore
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.io.File
import java.util.UUID

/**
 * The Sound Lab's library: what the app can play under a voice.
 *
 * Two kinds of thing live here and they behave differently on purpose.
 *
 * **Bundled assets** ship inside the APK — five beds and a needle drop, all generated by this project's own
 * synthesis script so there is no licensing question and nothing to download. They can be switched off
 * (the Sound Lab's own "do not offer me this one again") but never deleted: they are part of the app, and
 * deleting one would be deleting a feature.
 *
 * **Imported assets** are the user's own audio, brought in through the system picker. They are decoded to
 * the studio format once and stored as PCM in `files/assets`, so a record using them renders as fast as
 * one using a bundled bed, and so the original file — which lives outside the app and may be on a card
 * that gets removed — is never needed again.
 */
class AssetRepository(
    private val context: Context,
    private val dao: AudioAssetDao,
    private val files: FileStore,
) {

    private val bank = MusicBank(context, files)

    val assets: Flow<List<AudioAsset>> = dao.observeAll().map { rows -> rows.map { it.toModel() } }

    fun assetsIn(category: AssetCategory): Flow<List<AudioAsset>> =
        dao.observeByCategory(category.id).map { rows -> rows.map { it.toModel() } }

    /** Enabled background beds, which is what the Studio's music step shows. */
    val backgroundMusic: Flow<List<AudioAsset>> = assets.map { list ->
        list.filter { it.category == AssetCategory.BACKGROUND_MUSIC && it.enabled }
    }

    suspend fun find(id: String): AudioAsset? = dao.findById(id)?.toModel()

    suspend fun bundledCount(): Int = dao.countBundled()

    /**
     * Seeds the bundled assets on first launch and keeps them up to date afterwards.
     *
     * Matching is by resource name, not by id, so an install that already has these assets keeps whatever
     * the user decided about them — an asset switched off stays off across an app update. Durations are
     * measured once and stored, so the Sound Lab can show "0:32" without opening the file.
     */
    suspend fun syncBundled(): Int {
        var added = 0
        for (definition in AudioAsset.BUNDLED) {
            val existing = dao.findByResource(definition.bundledResourceName ?: continue)
            if (existing == null) {
                dao.upsert(AudioAssetEntity.from(definition))
                added++
            } else if (existing.title.isBlank() || existing.category != definition.category.id) {
                // The catalogue is the source of truth for what a bundled asset *is*; the user owns
                // everything else about it.
                dao.upsert(
                    AudioAssetEntity.from(
                        definition.copy(
                            id = existing.id,
                            enabled = existing.enabled,
                            trimStartMilliseconds = existing.trimStartMilliseconds,
                            trimEndMilliseconds = existing.trimEndMilliseconds,
                            defaultVolume = existing.defaultVolume,
                            createdAt = existing.createdAt,
                        ),
                    ),
                )
            }
        }
        measureMissingDurations()
        return added
    }

    /** Fills in durations and sizes for anything the catalogue has not measured yet. */
    suspend fun measureMissingDurations() {
        for (entity in dao.all()) {
            if (entity.durationMilliseconds > 0L && entity.sizeBytes > 0L) continue
            val asset = entity.toModel()
            val duration = bank.measureDurationMs(asset)
            val size = when {
                asset.isBundled -> files.assetFile(asset.id).takeIf { it.isFile }?.length() ?: 0L
                else -> asset.sourcePath?.let { File(it).length() } ?: 0L
            }
            if (duration > 0L || size > 0L) {
                dao.updateMeasured(entity.id, duration.coerceAtLeast(entity.durationMilliseconds), size)
            }
        }
    }

    /**
     * Imports an audio file the user picked.
     *
     * The decode happens here rather than at render time because it is the slow part and it is the part
     * that can fail: an unsupported file, a video whose audio track the codec cannot open, a document that
     * is actually a text file. Doing it in the Sound Lab means the failure is reported while the user is
     * looking at the import screen, and a record that references this asset can never fail to press
     * because of it.
     */
    suspend fun import(uri: Uri, fallbackTitle: String): ImportResult {
        val displayName = AudioDecoder.displayName(context, uri)
        val title = displayName.substringBeforeLast('.').replace('_', ' ').trim().ifBlank { fallbackTitle }

        val assetId = UUID.randomUUID().toString()
        val staging = File(files.stagingRoot(), "import-${assetId}")
        val staged = AudioDecoder.stageDocument(context, uri, staging)
            ?: return ImportResult.Failed("That file could not be opened.")

        val decodedTarget = files.assetFile(assetId, "wav")
        val decoded = try {
            AudioDecoder.decodeToWav(context, staged, decodedTarget, StudioFormat.SAMPLE_RATE)
        } finally {
            staged.delete()
        }

        if (decoded == null || decoded.durationMs <= 0L) {
            decodedTarget.delete()
            return ImportResult.Failed("That file could not be decoded as audio.")
        }

        val asset = AudioAsset(
            id = assetId,
            title = title.take(60),
            category = AssetCategory.BACKGROUND_MUSIC,
            sourcePath = decodedTarget.absolutePath,
            bundledResourceName = null,
            isBundled = false,
            enabled = true,
            defaultVolume = 0.18f,
            trimStartMilliseconds = 0L,
            trimEndMilliseconds = 0L,
            durationMilliseconds = decoded.durationMs,
            sizeBytes = decodedTarget.length(),
        )
        dao.upsert(AudioAssetEntity.from(asset))
        Log.i(TAG, "imported \"${asset.title}\" (${decoded.durationMs} ms)")
        return ImportResult.Imported(asset)
    }

    suspend fun setEnabled(id: String, enabled: Boolean) = dao.setEnabled(id, enabled)

    /**
     * Registers an asset that arrived inside a backup archive.
     *
     * The audio has already been extracted by the caller, and the archive's index carries the title, the
     * trim and the level, so the restored asset is the one the user had rather than a file named after its
     * own identifier. Compressed audio is decoded here — an archive could have been written by a build that
     * stored MP3s — but a file that is already PCM at the studio rate is moved rather than re-encoded, which
     * avoids a second generation of resampling.
     */
    suspend fun importRestoredAsset(
        id: String,
        extracted: File,
        extension: String,
        title: String = "",
        trimStartMs: Long = 0L,
        trimEndMs: Long = 0L,
        volume: Float = 0.18f,
        durationMs: Long = 0L,
    ): Boolean {
        val safeId = com.vynylrecord.app.core.storage.StorageLayout.safeId(id)
        val target = files.assetFile(safeId, "wav")
        return try {
            if (target.exists()) target.delete()
            val isProbablyPcm = extension.equals("wav", ignoreCase = true)
            if (isProbablyPcm) {
                extracted.copyTo(target, overwrite = true)
            } else {
                val decoded = AudioDecoder.decodeToWav(context, extracted, target, StudioFormat.SAMPLE_RATE)
                if (decoded == null) {
                    Log.w(TAG, "restored asset $id could not be decoded")
                    return false
                }
            }
            val asset = AudioAsset(
                id = safeId,
                title = title.ifBlank { extracted.nameWithoutExtension.replace('_', ' ').take(60) },
                category = AssetCategory.BACKGROUND_MUSIC,
                sourcePath = target.absolutePath,
                bundledResourceName = null,
                isBundled = false,
                enabled = true,
                defaultVolume = volume,
                trimStartMilliseconds = trimStartMs,
                trimEndMilliseconds = trimEndMs,
                durationMilliseconds = if (durationMs > 0L) durationMs else measureFile(target),
                sizeBytes = target.length(),
            )
            dao.upsert(AudioAssetEntity.from(asset))
            true
        } catch (error: Exception) {
            Log.w(TAG, "could not restore asset $id", error)
            target.delete()
            false
        }
    }

    /** The length of a decoded file, read from its header rather than by opening a codec. */
    private fun measureFile(file: File): Long = try {
        com.vynylrecord.app.core.audio.dsp.WavCodec.Reader(file).use { reader ->
            reader.frameCount * 1000L / reader.sampleRate
        }
    } catch (error: Exception) {
        0L
    }

    suspend fun setTrim(id: String, startMs: Long, endMs: Long, volume: Float) {
        val asset = dao.findById(id)?.toModel() ?: return
        val start = startMs.coerceIn(0L, (asset.durationMilliseconds - MIN_TRIM_MS).coerceAtLeast(0L))
        val end = when {
            endMs <= 0L -> asset.durationMilliseconds
            else -> endMs.coerceIn(start + MIN_TRIM_MS, asset.durationMilliseconds)
        }
        dao.updateTrim(id, start, end, volume.coerceIn(0f, 0.8f))
    }

    suspend fun rename(id: String, title: String) {
        val asset = dao.findById(id)?.toModel() ?: return
        dao.upsert(AudioAssetEntity.from(asset.copy(title = title.trim().take(60))))
    }

    /**
     * Deletes an imported asset and its file.
     *
     * A bundled asset cannot be deleted — the DAO's delete is filtered on `isBundled = 0`, so even a
     * mistaken call cannot remove something the app shipped with. Records that used the deleted asset
     * lose their background layer on the next press, which is the honest outcome: the audio is gone.
     */
    suspend fun delete(id: String): Boolean {
        val asset = dao.findById(id)?.toModel() ?: return false
        if (asset.isBundled) return false
        val removed = dao.deleteImported(id)
        if (removed > 0) {
            asset.sourcePath?.let { File(it).delete() }
            files.assetFile(id, "wav").delete()
            File(files.decodedRoot(), "$id.wav").delete()
        }
        return removed > 0
    }

    /** Storage held by imported assets, for the Settings panel. */
    suspend fun importedBytes(): Long = dao.all()
        .filter { !it.isBundled }
        .sumOf { it.sizeBytes }

    sealed interface ImportResult {
        data class Imported(val asset: AudioAsset) : ImportResult
        data class Failed(val message: String) : ImportResult
    }

    private companion object {
        const val TAG = "VynylAssetRepository"

        /** A background bed shorter than this is not worth trimming. */
        const val MIN_TRIM_MS = 500L
    }
}
